### ISSUE TITLE
add a NOTE to a proposal in writing phase to explain what is missing to manually move it to voting

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#106]
I have created a question on nightly, added some proposals and then wanted to move it to voting to test the triangle. There was no button in the UI so I could move it manually to voting. Is this correct ?

**Comment by pietrosperoni** [comment]
Hi @giovanisp , I don't know what the problem is. I have done the same, and after you write two proposals a button appears to move the question on. The button is on the question page. See:

![screen shot 2015-01-03 at 11 47 56](https://cloud.githubusercontent.com/assets/1333674/5602196/de669b36-933d-11e4-882d-144fee977c74.png)

Can you give us a screenshot? Thanks.

**Comment by giovanisp** [comment]
ok, if the question doesn't have at least two proposals it won't move. so that screen is only missing a note telling this. and maybe a call to action like "invite people to add more proposals" which links to the invitation screen.

**Comment by pietrosperoni** [comment]
> so that screen is only missing a note telling this. and maybe a call to action like "invite people to add more proposals" which links to the invitation screen.

Yes. :+1:

**Comment by giovanisp** [comment]
Need to check the template first.

**Comment by giovanisp** [comment]
ok for now.
