### ISSUE TITLE
Display better registration error messager

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-client#146]

**Comment by giovanisp** [comment]
what do you need, exactly ?

**Comment by giovanisp** [comment]
I left a note on the commit: Does this have to be generic? That it, if we know it happens when the username is already in use and someone is trying to register with the same username, we can tell them it is already registered and reset password (if active). Or to offer to resend activation code or look at spam folder to activate (if the account is not yet active).

**Comment by derekpa** [comment]
I opened the issue because you drew attention to the fact that the error when registering was generic. I fixed it so the correct messages returned from the server were displayed: "that username already taken", that kind of thing. Nothing else needs to be done here for the moment.
