### ISSUE TITLE
Discussion screen should list whole text.

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#238]
When trying to write a comment for a point I find myself having to close the dialog to see the full text of what I'm commenting on. I think this screen should have the full proposal text...

![screen shot 2015-02-23 at 11 08 04](https://cloud.githubusercontent.com/assets/1789426/6326712/634413f2-bb4c-11e4-989a-619a9f630676.png)

**Comment by giovanisp** [comment]
This is another modal that will disappear as it is...

Inviato da iPad

**Comment by pietrosperoni** [comment]
But even once the modal goes, we still will have to deal with limited space, and right now the modal window is basically using up ALL the space of the window, so it is not like we will have huge more space. I suspect this will be a problem we still will need to solve.

Should I reopen it?

**Comment by giovanisp** [comment]
Modals are not the only way to handle too much text on limited screen space. We can have responsive sliding panels for each "action" so the user can focus on each task (i.e voting on the triangle) without losing control of other possible actions (commenting pro/con, asking or answering clarifications...). anyway there is another issue about using pages instead of modals.

**Comment by vvorski** [comment]
It seems to me btw. that there is a lot of discussion about the details when what is really needed is that full and thorough proper UI design to give good usability based on user stories.
