### ISSUE TITLE
get rid of rounded corners in CSS

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#251]
I think rounded corners are "outdated"... What about following something more like a flat design getting rid of all rounded corners, from dialog modals to buttons ?  We can comment the CSS and see how it looks like. I think it makes it much less "bootstrap out-of-the-box".

**Comment by pietrosperoni** [comment]
LOL!
fashion.
Ok, as you please :-)

**Comment by giovanisp** [comment]
... and don't laugh !  :-)

**Comment by derekpa** [comment]
Twitter has them :-) 

What websites are you looking at as your modern style icons?

**Comment by giovanisp** [comment]
many ... not only for buttons but modals as well and internal color boxes... I'd give a shot commenting out the rounded-corners we are using now. I think that it could help to address @vvorski concers of the "default" bootstrap theme we still have to solve in next releases. For now it could be enough.

![image](https://cloud.githubusercontent.com/assets/180794/6443435/2a415c12-c0f7-11e4-87d3-f77b4f1fd440.png)

![image](https://cloud.githubusercontent.com/assets/180794/6443382/d01b1908-c0f6-11e4-8ae7-3ba49ad54468.png)

![image](https://cloud.githubusercontent.com/assets/180794/6443404/f473a8d8-c0f6-11e4-8d3f-0e385f1fb422.png)

![image](https://cloud.githubusercontent.com/assets/180794/6443444/34bf703e-c0f7-11e4-8bf8-56bbb2ee292f.png)

![image](https://cloud.githubusercontent.com/assets/180794/6443577/1a9cba94-c0f8-11e4-9b10-eabf5a6d5db7.png)

**Comment by vvorski** [comment]
Yes, need to move to a more professional looking UI. For a start one of the bootstrap themes might be good enough... http://designmodo.com/flat/

For inspiration I think going flat-design is the easiest and safest way to create a modern-feel UI...

http://fltdsgn.com/


Victor Vorski
victor@vorski.com　skype:vvorski

**Comment by giovanisp** [comment]
needs LESS compiling and deploy on test  :)

**Comment by derekpa** [comment]
OK, so you're doing it.

**Comment by derekpa** [comment]
Looks awful - but what do I know about fashion :-)

**Comment by giovanisp** [comment]
Awful?
I think it was great! 
Needs minor css adjustments for some spacing, but I think it is aligned with very very simple flat design. we also need more color-coding.
i have several mockups in mind for the home, but I am simply lacking time to do it :-(

Inviato da iPad

**Comment by pietrosperoni** [comment]
Guys, let's focus on the actual mechanism. The rounded corner or flat design can wait.

**Comment by pietrosperoni** [comment]
(And, btw, I agree with Derek that the flat design looks awful, but then again @vvorski link: http://designmodo.com/flat/ shows a flat design really nice. But still can you imagine someone not using the system because it has rounded corners? And someone not using the system because the result is not good enough?

In every case at some point we are going to really focus on the UI, but it is not now.

**Comment by vvorski** [comment]
"But still can you imagine someone not using the system because it has
rounded corners? "

Well this is a philosophical question. At which point is beauty important?
How much effort should be spent on making something pleasing to the eye
.vs. functionality?

After 15 years in Japan which has some of the most hideous urban
architecture and public works in the world I feel I understand well what
happens when you let engineers run the show and everything is built for
functionality whilst ignoring esthetics... I'd say you Europeans don't even
understand how horrid an environment that creates because in Europe
esthetics as an integral part of the design process is taken as a given.

But yes, obviously it is about the right timing.

V/.

Victor Vorski

victor@vorski.com skype:vvorski

**Comment by giovanisp** [comment]
moved to #262
