### ISSUE TITLE
I am not allowed to comment, but the screen allows inputing a comment

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#280]
This is really not nice. I wrote a long comment and the system now tells me it can't post it.

If comments are not allowed, then this screen should be blocked totally.

![screen shot 2015-03-18 at 10 01 47](https://cloud.githubusercontent.com/assets/1789426/6706478/fac58466-cd55-11e4-8672-0f761796755f.png)

**Comment by giovanisp** [comment]
Totally agree !!!!

**Comment by pietrosperoni** [comment]
Sorry @vvorski . I know how much that sucks.

**Comment by derekpa** [comment]
Actually I forget, did we ever decide whether comments should only be added during voting as it used to be? Can't remember.

**Comment by giovanisp** [comment]
Yes, for now, only during voting.

**Comment by giovanisp** [comment]
Now the page opens up totally blank. Can't we simply hide the icons (and links) so the user don't even see the functionality since it is not allowed ? A couple of IF's would suffice :-) 
![image](https://cloud.githubusercontent.com/assets/180794/6960684/2fe8f062-d925-11e4-85d8-f4314d945a5f.png)
![image](https://cloud.githubusercontent.com/assets/180794/6960727/42b3c708-d925-11e4-9282-b419f724c4a8.png)
